CREATE ROLE adm LOGIN ENCRYPTED PASSWORD 'adm' SUPERUSER;
CREATE ROLE usr LOGIN ENCRYPTED PASSWORD 'usr' NOSUPERUSER NOINHERIT NOCREATEROLE;

CREATE DATABASE "POSHotel"
	WITH OWNER = adm
		ENCODING = 'UTF8'
		TABLESPACE = pg_default
		CONNECTION LIMIT = -1;

-- CREATE SCHEMA dbhotel AUTHORIZATION adm;
-- GRANT CREATE ON SCHEMA dbhotel TO adm;
-- GRANT USAGE ON SCHEMA dbhotel TO adm;
-- 
-- GRANT USAGE ON SCHEMA dbhotel TO usr;
-- GRANT USAGE ON SCHEMA dbhotel TO public;